-- Josh Grey
USE PizzaDB;
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Pepperoni', 2, 2.75, 3.5, 4.5, 1.25, 0.2, 50, 100);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Sausage', 2.5, 3, 3.5, 4.25, 1.25, 0.15, 50, 100);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Ham', 2, 2.5, 3.25, 4, 1.5, 0.15, 25, 78);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Chicken', 1.5, 2, 2.25, 3, 1.75, 0.25, 25, 56);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Green Pepper', 1, 1.5, 2, 2.5, 0.5, 0.02,25, 79);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Onion', 1, 1.5, 2, 2.75, 0.5, 0.02, 25, 85);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Roma Tomato', 2, 3, 3.5, 4.5, 0.75, 0.03, 10, 86);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Mushrooms', 1.5, 2, 2.5, 3, 0.75, 0.1, 50, 52);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Black Olives', 0.75, 1,1.5, 2, 0.6, 0.1, 25, 39);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Pineapple', 1, 1.25, 1.75, 2, 1, 0.25, 0, 15);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Jalapenos', 0.5, 0.75, 1.25, 1.75, 0.5, 0.05, 0, 64);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Banana Peppers', 0.6, 1, 1.3, 1.75, 0.5, 0.05, 0, 36);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Regular Cheese', 2, 3.5, 5, 7, 0.5, 0.12, 50, 250);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Four Cheese Blend', 2, 3.5, 5, 7, 1, 0.15, 25, 150);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Feta Cheese', 1.75, 3, 4, 5.5, 1.5, 0.18, 0, 75);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Goat Cheese', 1.6, 2.75, 4, 5.5, 1.5, 0.2, 0, 54);
INSERT INTO topping (topping_TopName, topping_SmallAMT, topping_MedAMT, topping_LgAMT, topping_XLAMT, topping_CustPrice, topping_BusPrice, topping_MinINVT, topping_CurINVT) VALUES ('Bacon', 1, 1.5, 2, 3, 1.5, 0.25, 0, 89);
INSERT INTO discount (discount_DiscountName, discount_Amount, discount_IsPercent) VALUES ('Employee', 15, TRUE);
INSERT INTO discount (discount_DiscountName, discount_Amount, discount_IsPercent) VALUES ('Lunch Special Medium', 1, FALSE);
INSERT INTO discount (discount_DiscountName, discount_Amount, discount_IsPercent) VALUES ('Lunch Special Large', 2, FALSE);
INSERT INTO discount (discount_DiscountName, discount_Amount, discount_IsPercent) VALUES ('Specialty Pizza', 1.5, FALSE);
INSERT INTO discount (discount_DiscountName, discount_Amount, discount_IsPercent) VALUES ('Happy Hour', 10, TRUE);
INSERT INTO discount (discount_DiscountName, discount_Amount, discount_IsPercent) VALUES ('Gameday Special', 20, TRUE);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Small', 'Thin', 3, 0.5);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Small', 'Original', 3, 0.75);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Small', 'Pan', 3.5, 1);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Small', 'Gluten-Free', 4, 2);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Medium', 'Thin', 5, 1);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Medium', 'Original', 5, 1.5);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Medium', 'Pan', 6, 2.25);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Medium', 'Gluten-Free', 6.25, 3);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Large', 'Thin', 8, 1.25);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Large', 'Original', 8, 2);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Large', 'Pan', 9, 3);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('Large', 'Gluten-Free', 9.5, 4);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('XLarge', 'Thin', 10, 2);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('XLarge', 'Original', 10, 3);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('XLarge', 'Pan', 11.5, 4.5);
INSERT INTO baseprice (baseprice_Size, baseprice_CrustType, baseprice_CustPrice, baseprice_BusPrice) VALUES ('XLarge', 'Gluten-Free', 12.5, 6);
INSERT INTO customer (customer_FName, customer_LName, customer_PhoneNum) VALUES ('Andrew', 'Wilkes-Krier', '8642545861');
INSERT INTO customer (customer_FName, customer_LName, customer_PhoneNum) VALUES ('Matt', 'Engers', '8644749953');
INSERT INTO customer (customer_FName, customer_LName, customer_PhoneNum) VALUES ('Frank', 'Turner', '8642328944');
INSERT INTO customer (customer_FName, customer_LName, customer_PhoneNum) VALUES ('Milo', 'Auckerman', '8648785679');
INSERT INTO ordertable (customer_CustID, ordertable_OrderType, ordertable_OrderDateTime, ordertable_CustPrice, ordertable_BusPrice, ordertable_isComplete) VALUES (NULL, 'dinein', '2025-03-05 12:03:00', 19.75, 3.68, 1);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Large', 'Thin', 'completed', '2025-03-05 12:03:00', 19.75, 3.68, 1);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (1, 13, 1);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (1, 1, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (1, 2, 0);
INSERT INTO pizza_discount (pizza_PizzaID, discount_DiscountID) VALUES (1, 3);
INSERT INTO dinein (ordertable_OrderID, dinein_TableNum) VALUES (1, 21);
INSERT INTO ordertable (customer_CustID, ordertable_OrderType, ordertable_OrderDateTime, ordertable_CustPrice, ordertable_BusPrice, ordertable_isComplete) VALUES (NULL, 'dinein', '2025-04-03 12:05:00', 19.78, 4.63, 1);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Medium', 'Pan', 'completed', '2025-04-03 12:05:00', 12.85, 3.23, 2);
INSERT INTO dinein (ordertable_OrderID, dinein_TableNum) VALUES (2, 4);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (2, 15,0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (2, 9, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (2, 7, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (2, 8, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (2, 12, 0);
INSERT INTO pizza_discount (pizza_PizzaID, discount_DiscountID) VALUES (2, 2);
INSERT INTO pizza_discount (pizza_PizzaID, discount_DiscountID) VALUES (2, 4);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Small', 'Original', 'completed', '2025-04-03 12:05:00', 6.93, 1.40, 2);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (3, 13, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (3, 4, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (3, 12, 0);
INSERT INTO ordertable (customer_CustID, ordertable_OrderType, ordertable_OrderDateTime, ordertable_CustPrice, ordertable_BusPrice, ordertable_isComplete) VALUES (1, 'pickup', '2025-03-03 21:30:00', 89.28, 19.80, 1);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Large', 'Original', 'completed', '2025-03-03 21:30:00', 14.88, 3.30, 3);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (4, 13, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (4, 1, 0);
INSERT INTO pickup (ordertable_OrderID, pickup_IsPickedUp) VALUES (3, TRUE);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Large', 'Original', 'completed', '2025-03-03 21:30:00', 14.88, 3.30, 3);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (5, 13, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (5, 1, 0);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Large', 'Original', 'completed', '2025-03-03 21:30:00', 14.88, 3.30, 3);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (6, 13, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (6, 1, 0);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Large', 'Original', 'completed', '2025-03-03 21:30:00', 14.88, 3.30, 3);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (7, 13, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (7, 1, 0);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Large', 'Original', 'completed', '2025-03-03 21:30:00', 14.88, 3.30, 3);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (8, 13, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (8, 1, 0);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Large', 'Original', 'completed', '2025-03-03 21:30:00', 14.88, 3.30, 3);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (9, 13, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (9, 1, 0);
INSERT INTO ordertable (customer_CustID, ordertable_OrderType, ordertable_OrderDateTime, ordertable_CustPrice, ordertable_BusPrice, ordertable_isComplete) VALUES (1, 'delivery', '2025-04-20 19:11:00', 68.95, 20.99, 1);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('XLarge', 'Original', 'completed', '2025-04-20 19:11:00', 27.94, 9.19, 4);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (10, 1, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (10, 2, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (10, 14, 0);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('XLarge', 'Original', 'completed', '2025-04-20 19:11:00', 31.50, 6.25, 4);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (11, 3, 1);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (11, 10, 1);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (11, 14, 0);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('XLarge', 'Original', 'completed', '2025-04-20 19:11:00', 26.75, 5.55, 4);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (12, 4, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (12, 17, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (12, 14, 0);
INSERT INTO order_discount (ordertable_OrderID, discount_DiscountID) VALUES (4, 6);
INSERT INTO pizza_discount (pizza_PizzaID, discount_DiscountID) VALUES (11, 4);
INSERT INTO delivery (ordertable_OrderID, delivery_HouseNum, delivery_Street, delivery_City, delivery_State, delivery_Zip, delivery_IsDelivered) VALUES (4, 115, 'Party Blvd', 'Anderson', 'SC', 29621, TRUE);
INSERT INTO ordertable (customer_CustID, ordertable_OrderType, ordertable_OrderDateTime, ordertable_CustPrice, ordertable_BusPrice, ordertable_isComplete) VALUES (2, 'pickup', '2025-03-02 17:30:00', 28.70, 7.84, 1);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('XLarge', 'Gluten-Free','completed', '2025-03-02 17:30:00', 28.70, 7.84, 5);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (13, 5, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (13, 6, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (13, 7, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (13, 8, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (13, 9, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (13, 16, 0);
INSERT INTO pizza_discount (pizza_PizzaID, discount_DiscountID) VALUES (13, 4);
INSERT INTO pickup (ordertable_OrderID, pickup_IsPickedUp) VALUES (5, TRUE);
INSERT INTO ordertable (customer_CustID, ordertable_OrderType, ordertable_OrderDateTime, ordertable_CustPrice, ordertable_BusPrice, ordertable_isComplete) VALUES (3, 'delivery', '2025-03-02 18:17:00', 25.81, 3.64, 1);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Large', 'Thin', 'completed', '2025-03-02 18:17:00', 25.81, 3.64, 6);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (14, 4, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (14, 5, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (14, 6, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (14, 8, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (14, 14, 1);
INSERT INTO delivery (ordertable_OrderID, delivery_HouseNum, delivery_Street, delivery_City, delivery_State, delivery_Zip, delivery_IsDelivered) VALUES (6, 6745, 'Wessex St', 'Anderson', 'SC', 29621, 1);
INSERT INTO ordertable (customer_CustID, ordertable_OrderType, ordertable_OrderDateTime, ordertable_CustPrice, ordertable_BusPrice, ordertable_isComplete) VALUES (4, 'delivery', '2025-04-13 20:32:00', 31.66, 6.00, 1);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Large', 'Thin', 'completed', '2025-04-13 20:32:00', 18.00, 2.75, 7);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (15, 14, 1);
INSERT INTO pizza (pizza_Size, pizza_CrustType, pizza_PizzaState, pizza_PizzaDate, pizza_CustPrice, pizza_BusPrice, ordertable_OrderID) VALUES ('Large', 'Thin', 'completed', '2025-04-13 20:32:00', 19.25, 3.25, 7);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (16, 13, 0);
INSERT INTO pizza_topping (pizza_PizzaID, topping_TopID, pizza_topping_IsDouble) VALUES (16, 1, 1);
INSERT INTO order_discount (ordertable_OrderID, discount_DiscountID) VALUES (7, 1);
INSERT INTO delivery (ordertable_OrderID, delivery_HouseNum, delivery_Street, delivery_City, delivery_State, delivery_Zip, delivery_IsDelivered) VALUES (7, 8879, 'Suburban', 'Anderson', 'SC', 29621, 1);
